### ISSUE TITLE
API design: let users handle error codes without throwing error

### ISSUE THREAD

**Issue by matbesancon** [JuliaSmoothOptimizers/BasicLU.jl#28]
Julia idiom is to throw error on incorrect behaviors, instead of error codes / types or results as in other languages.

Unfortunately, this assumes preventing the error is cheap enough that the check can be done twice. For the heavy-lifting functions here (e.g. the solving functions here), checking that the matrix is not singular beforehand can be heavy, it could be preferable to allow the user to get the retcode themselves instead of the `checkretcode` mechanism.

A typical example I have now:

```julia
    piverr = try
        BasicLU.solve_for_update(F, colidx)
        BasicLU.update(F, piv)
    catch e
        @warn "Factorization error\n$e"
        Inf
    end
    if piverr > maxerrortol
        # refactor from scratch
        BasicLU.factorize(F, M)
    end
```

while a `retcode` could avoid the try/catch mechanism which is definitely slower for a hot loop

**Comment by amontoison** [comment]
Can you open a PR Mathieu?

**Comment by matbesancon** [comment]
not at the moment (in the next weeks) but if it becomes a bottleneck in my current implementation I'll give it a shot yes
