### ISSUE TITLE
Deactivate print statements

### ISSUE THREAD

**Issue by mtanneau** [JuliaSmoothOptimizers/BasicLU.jl#8]
I'm using the `maxvolume_basis` function in an internal loop; can we have the option to deactivate that print statement?

https://github.com/JuliaSmoothOptimizers/BasicLU.jl/blob/2b249495ea3c1ea2f553a4ac7f810f1d93ff5aa3/src/BasicLU.jl#L550

**Comment by amontoison** [comment]
Fixed by #9
